### ISSUE TITLE
Goal Tracking CV

### ISSUE THREAD

**Issue by akiyeng2** [Team-4795/2022-Rapid-React#21]
Create CV code that can align horizontally with goal

- [x] Communicate about mounting requirements to mech/design
- [x] Add tape to goal
- [x] Create and test photonvision pipeline
- [x] Connect to robot
- [x] Write CV code on robot for alignment
- [x] Add mount to practice bot, test
- [x] Create test plan
- [x] Calibrate camera
- [x] Horizontal alignment

Nice-to-haves

- [x] Calculate distance
- [x] Determine shooter speeds based off distance

**Comment by ryan-huang1** [comment]
the high goal has reflective tape attached with the right intervals

**Comment by fategg555** [comment]
I think this task is done - I think the main thing is to tune the target to the environment each time, but I think we have done the hard part of getting the system working. I think we can close this issue.
